### PR TITLE
 respect local ignore file irrespective of current work dir #4 

### PR DESCRIPTION
**Pull request by Konfekt**
As discussed at https://github.com/panozzaj/vim-copilot-ignore/issues/4

### CODE REVIEW

**Comment by Konfekt** [comment]
Just let me know if I forgot about something

**Comment by Konfekt** [comment]
I guess you're wondering why not simply

```vim
findfile('.copilotignore', getcwd(-1)..';')
```

instead of the manual 

```vim
function! s:FindCopilotIgnore(dir) abort
    let current_dir = a:dir
    while !(current_dir ==# $HOME || current_dir ==# '/' || current_dir =~# '^[A-Za-z]:\\\?$' || current_dir ==# '\\')
        if filereadable(current_dir..s:slash..'.copilotignore')
            return current_dir..s:slash..'.copilotignore'
        endif
        let parent_dir = fnamemodify(current_dir, ':h')
        if current_dir ==# parent_dir
          return ''
        else
          let current_dir = parent_dir
        endif
    endwhile
    return ''
endfunction
```

?

**Comment by panozzaj** [comment]
Hi, sorry for the delay. I just have not found the time the last couple of weeks but I hope to get to this soon.

**Comment by panozzaj** [comment]
I took a look and tweaked a couple of small things in the code (whitespace mostly, I believe) and updated the README changes based on my understanding of what was happening. Since it seemed to work based on my testing, I merged this. Thanks again for submitting this!

**Pull request merged**
